name: Ping Cron Endpoint

on:
  # schedule:
  #   - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call cron endpoint
        env:
          CRON_SECRET: ${{ secrets.CRON_ROUTE_SECRET }}
          CRON_URL: ${{ secrets.CRON_ENDPOINT_URL }}
        run: |
          if [ -z "$CRON_SECRET" ] || [ -z "$CRON_URL" ]; then
            echo "CRON_SECRET or CRON_URL not set."
            exit 1
          fi
          curl -X POST "$CRON_URL" -H "Authorization: Bearer $CRON_SECRET" -H "Content-Type: application/json" -f
